services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: cnc_calc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cnc_pg:/var/lib/postgresql/data
volumes:
  cnc_pg:
